test:
  test_interval: 1
  restore_path: ./checkpoints/finetune/
  checkpoints: [checkpoint34, checkpoint116]
  log_interval: 20
  num_workers: 1
  save: True
  save_path: ./output/chiral/testing
  property: top_score
  batch_size: 96
  seed: 2021
  margin: '<='

data:
  block_dir: /data/people/kabeywar/datasets/chiral/docking

model:
  name: chiral_finetune_scratch2
  hidden_dim: 128
  attention: true
  n_layers: 7
  max_atom_type: 100
  charge_power: 2
  cutoff: 5.0
  no_edge_types: False
  layernorm: False
  order: 3
  collate: False